query AllInterviews($first: IntType = 100, $skip: IntType = 0) {
	allInterviews(first: $first, skip: $skip) {
		...InterviewFragmentLight
	}
	_allInterviewsMeta {
		count
	}
}

query Interview($slug: String) {
	interview(filter: { slug: { eq: $slug } }) {
		...InterviewFragment
	}
}

query AllInterviewsCategories($first: IntType = 100, $skip: IntType = 0) {
	allInterviewCategories(first: $first, skip: $skip, orderBy: [title_ASC]) {
		id
		title
	}
	_allInterviewsMeta {
		count
	}
}

fragment InterviewFragment on InterviewRecord {
	_createdAt
	id
	intro(markdown: false)
	title
	slug
	category {
		id
		title
	}
	image {
		...ImageFragment
	}
	content {
		value
		blocks {
			__typename
			... on ImageRecord {
				__typename
				id
				layout
				image {
					...ImageFragment
				}
			}
			... on ImageGalleryRecord {
				__typename
				id
				images {
					...ImageThumbnailFragment
				}
			}
			... on LinkButtonRecord {
				__typename
				id
				link {
					__typename
					... on ExternalLinkRecord {
						__typename
						id
						title
						url
					}
					... on InternalLinkRecord {
						__typename
						id
						record {
							... on AboutRecord {
								id
								slug
								title
							}
							... on NewsRecord {
								id
								slug
								title
							}
							... on InterviewRecord {
								id
								slug
							}
						}
					}
				}
			}
			... on VideoRecord {
				__typename
				id
				title
				video {
					height
					width
					title
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
			... on RecordInterface {
				__typename
				id
			}
		}
	}
	_seoMetaTags {
		...SeoMetaTagsFragment
	}
}

fragment InterviewFragmentLight on InterviewRecord {
	id
	intro(markdown: false)
	title
	category {
		id
		title
	}
	image {
		...ImageThumbnailFragment
	}
	slug
	_createdAt
}
