query AllRecipes($first: IntType = 100, $skip: IntType = 0) {
	allRecipes(first: $first, skip: $skip) {
		...RecipeFragmentLight
	}
	_allRecipesMeta {
		count
	}
}

query Recipe($slug: String!) {
	recipe(filter: { slug: { eq: $slug } }) {
		...RecipeFragment
	}
}

query AllRecipeCategories($first: IntType = 100, $skip: IntType = 0) {
	allRecipeCategories(first: $first, skip: $skip, orderBy: [title_ASC]) {
		id
		title
		slug
	}
	_allRecipeCategoriesMeta {
		count
	}
}

fragment RecipeFragment on RecipeRecord {
	__typename
	_modelApiKey
	id
	title
	image {
		...ImageFragment
	}
	thumb: image {
		...ImageThumbnailFragment
	}
	intro(markdown: false)
	category {
		id
		title
		slug
	}
	slug
	content {
		value
		blocks {
			__typename
			... on ImageRecord {
				__typename
				id
				layout
				image {
					...ImageFragment
				}
			}
			... on ImageGalleryRecord {
				__typename
				id
				images {
					...ImageThumbnailFragment
				}
			}
			... on LinkButtonRecord {
				__typename
				id
				link {
					__typename
					... on ExternalLinkRecord {
						__typename
						id
						title
						url
					}
					... on InternalLinkRecord {
						__typename
						id
						record {
							... on AboutRecord {
								id
								slug
								title
							}
							... on RecipeRecord {
								id
								slug
								title
							}
						}
					}
				}
			}
			... on VideoRecord {
				__typename
				id
				title
				video {
					height
					width
					title
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
			... on RecordInterface {
				__typename
				id
			}
		}
	}
	_seoMetaTags {
		...SeoMetaTagsFragment
	}
}

fragment RecipeFragmentLight on RecipeRecord {
	__typename
	_modelApiKey
	id
	title
	intro(markdown: false)
	category {
		id
		title
		slug
	}
	image {
		...ImageThumbnailFragment
	}
	slug
}

fragment SeoMetaTagsFragment on Tag {
	attributes
	content
	tag
}
