query SiteSearch(
	$aboutIds: [ItemId]
	$recipeIds: [ItemId]
	$interviewIds: [ItemId]
	$youthIds: [ItemId]
	$tipIds: [ItemId]
	$first: IntType = 100
	$skip: IntType = 0
) {
	allAbouts(first: $first, skip: $skip, filter: { id: { in: $aboutIds } }) {
		__typename
		_modelApiKey
		title
		text: intro(markdown: false)
		slug
	}
	allRecipes(first: $first, skip: $skip, filter: { id: { in: $recipeIds } }) {
		__typename
		_modelApiKey
		title
		text: intro(markdown: false)
		slug
	}
	allInterviews(first: $first, skip: $skip, filter: { id: { in: $interviewIds } }) {
		__typename
		_modelApiKey
		title
		text: intro(markdown: false)
		slug
	}
	allYouths(
		first: $first
		skip: $skip

		filter: { id: { in: $youthIds } }
	) {
		__typename
		_modelApiKey
		title
		text: intro(markdown: false)
		slug
	}
	allTips(first: $first, skip: $skip, filter: { id: { in: $tipIds } }) {
		__typename
		_modelApiKey
		title: name
		text: intro(markdown: false)
		slug
	}
}
