query Sitemap($first: IntType = 500, $skip: IntType = 0) {
	allAbouts(first: $first, skip: $skip) {
		slug
		title
		_updatedAt
	}
	_allAboutsMeta {
		count
	}
	allNews(first: $first, skip: $skip) {
		title
		slug
		_updatedAt
	}
	_allNewsMeta {
		count
	}
	allInterviews(first: $first, skip: $skip) {
		title
		slug
		_updatedAt
	}
	_allInterviewsMeta {
		count
	}
	allRecipes(first: $first, skip: $skip) {
		title
		slug
		_updatedAt
	}
	_allRecipesMeta {
		count
	}
	allTips(first: $first, skip: $skip) {
		title
		slug
		_updatedAt
	}
	_allTipsMeta {
		count
	}
}
