query AllTips($first: IntType = 100, $skip: IntType = 0) {
	allTips(first: $first, skip: $skip) {
		...TipFragmentLight
	}
	_allTipsMeta {
		count
	}
}

query Tip($slug: String!) {
	tip(filter: { slug: { eq: $slug } }) {
		...TipFragment
	}
}

query AllTipsCategories($first: IntType = 100, $skip: IntType = 0) {
	allTipCategories(first: $first, skip: $skip, orderBy: [title_ASC]) {
		id
		title
	}
	_allTipCategoriesMeta {
		count
	}
}

fragment TipFragment on TipRecord {
	_createdAt
	id
	intro(markdown: false)
	name
	slug
	image {
		...ImageFragment
	}
	category {
		id
		title
	}
	content {
		value
		blocks {
			__typename
			... on ImageRecord {
				__typename
				id
				layout
				image {
					...ImageFragment
				}
			}
			... on ImageGalleryRecord {
				__typename
				id
				images {
					...ImageThumbnailFragment
				}
			}
			... on LinkButtonRecord {
				__typename
				id
				link {
					__typename
					... on ExternalLinkRecord {
						__typename
						id
						title
						url
					}
					... on InternalLinkRecord {
						__typename
						id
						record {
							... on AboutRecord {
								id
								slug
								title
							}
							... on NewsRecord {
								id
								slug
								title
							}
						}
					}
				}
			}
			... on VideoRecord {
				__typename
				id
				title
				video {
					height
					width
					title
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
			... on RecordInterface {
				__typename
				id
			}
		}
	}
	_seoMetaTags {
		...SeoMetaTagsFragment
	}
}

fragment TipFragmentLight on TipRecord {
	id
	intro(markdown: false)
	name
	image {
		...ImageThumbnailFragment
	}
	category {
		id
		title
	}
	slug
}
