query AllYouths($first: IntType = 100, $skip: IntType = 0) {
	allYouths(first: $first, skip: $skip, orderBy: [_createdAt_DESC]) {
		...YouthFragmentLight
	}

	_allYouthsMeta {
		count
	}
}

query Youth($slug: String!) {
	youth(filter: { slug: { eq: $slug } }) {
		...YouthFragment
	}
}

query AllYouthsCategories($first: IntType = 100, $skip: IntType = 0) {
	allYouthCategories(first: $first, skip: $skip, orderBy: [title_ASC]) {
		id
		title
	}
	_allYouthCategoriesMeta {
		count
	}
}

fragment YouthFragment on YouthRecord {
	id
	title
	image {
		...ImageFragment
	}
	intro(markdown: false)
	slug
	category {
		id
		title
	}
	content {
		value
		blocks {
			__typename
			... on ImageRecord {
				__typename
				id
				layout
				image {
					...ImageFragment
				}
			}
			... on ImageGalleryRecord {
				__typename
				id
				images {
					...ImageThumbnailFragment
				}
			}
			... on LinkButtonRecord {
				__typename
				id
				link {
					__typename
					... on ExternalLinkRecord {
						__typename
						id
						title
						url
					}
					... on InternalLinkRecord {
						__typename
						id
						record {
							... on AboutRecord {
								id
								slug
								title
							}
							... on NewsRecord {
								id
								slug
								title
							}
						}
					}
				}
			}
			... on VideoRecord {
				__typename
				id
				title
				video {
					height
					width
					title
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
			... on RecordInterface {
				__typename
				id
			}
		}
	}
	_seoMetaTags {
		...SeoMetaTagsFragment
	}
}

fragment YouthFragmentLight on YouthRecord {
	id
	title
	intro(markdown: false)
	slug
	category {
		id
		title
	}
	image {
		...ImageThumbnailFragment
	}
}
